books/urls.py
from django.urls import path
from . import views

app_name = 'books'
 
urlpatterns = [
   path('', views.books, name="list"),
   path('add_form/', views.add, name="add"),
   path('delete/', views.delete, name="delete"),
   path('search/', views.search, name="search")
]

library/urls.py
from django.conf.urls import include
from django.urls import path
from django.contrib import admin
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/',include('books.urls')),
    path('',include('books.urls'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from enum import Enum
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class BookType(Enum):
    ten_days = 1
    five_days = 2
    two_days = 3
 
class Book(models.Model):
    
    class BookType2(models.IntegerChoices):
        ten_days = 1, "Ten Days Loan"
        five_days = 2, "Five Days Loan"
        two_days = 3, "Two Days Loan"

    name = models.CharField(max_length=200, null=False)
    author = models.CharField(max_length=200, null=False)
    year_published = models.DateField()
    type = models.SmallIntegerField(null=False, default = BookType2.two_days, choices=BookType2.choices)
    created_time=models.DateTimeField(auto_now_add=True)
    image = models.ImageField(null=True, blank=True, default='placeholder/')
    
    def __str__(self):
        return self.name

class Loan(models.Model):
    custID = models.ForeignKey(User, on_delete=models.CASCADE,)
    bookID = models.ForeignKey(Book, on_delete=models.CASCADE,)
    loan_date=models.DateTimeField()
    return_date=models.DateTimeField()



# https://docs.djangoproject.com/en/4.1/ref/models/fields/#field-choices-enum-types

books/forms.py
from django.forms import ModelForm
from .models import Book
 
class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ['name', 'author', 'year_published', 'type', 'image'] 

books/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.template import loader

from books.forms import BookForm
from books.models import Book


def books(request):
    my_books = Book.objects.all()
    context = {
       'book_list': my_books
    }
    return render(request,'books.html', context=context)


def add(request):
    if request.method == 'POST':
        book_form = BookForm(request.POST , request.FILES)
        if book_form.is_valid():
            book_form.save()
            return redirect('books:list')  
    else:
        bookform = BookForm()
   
    context = {
        'bookform': bookform,
    }
    return render(request, "add_form.html", context=context)


def delete(request):
    return HttpResponse("DELETED")

def search(request):
    search = request.GET.get('search')
   
    my_books = Book.objects.filter(name__contains=search).values() | Book.objects.filter(author__contains=search).values()
    context = {
       'book_list': my_books
    }
    return render(request,'books.html', context=context)

books/templates/add_form.html
{% extends "base.html" %}
{%block body%}
 

<form action="{% url 'books:add' %}" method="POST" enctype=multipart/form-data>
    <tr>
    {% csrf_token %}
    {{ bookform.as_table  }}
    <input type="submit">
</tr>
 </form>


{%endblock%}

books/templates/books.html
{% extends "base.html" %}
{% load static %}
{%block body%}
  <div class="card-deck">
      {%for book in book_list%}
      <div class="card">
        <div class="card-body">
          <img style="width:314px;height:314px" src="/static/images/{{ book.image }}" class="card-img-top"  alt="...">

          <h5 class="card-title">{{book.name}}</h5>
          <p class="card-text">{{book.author}}</p>
          <p class="card-text"><small class="text-muted">{{book.year_published}}</small></p>
          <a href="{% url 'books:delete' %}" class="btn btn-danger">DELETE</a>
        </div>
      </div>
      {%endfor%}
  </div>
      
  {%endblock%}


templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <title>Document</title>
</head>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'books:list' %}">BOOK LIST <span class="sr-only"></span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'books:add' %}">Add a book</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/login/login">LOG-IN</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0" action="{% url 'books:search' %}">
        <input name="search" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
<body>

{%block body%}

{%endblock%}


</body>
</html>